name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: Jfrog github integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install mypy black ruff pydantic sqlalchemy
          python -m pip install build
      - name: Create  artifact dist folder
        run: |
          mkdir dist
          sudo apt update
          sudo apt install tar gzip build-essential
          cd  dist
      - name: Code Build
        run: |
          python -m build
      - name: upload all aritifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Setup JFrog CLI for integration
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.INSIGHT_CENTER_FRONTEND_SITE_JFROG_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.INSIGHT_CENTER_FRONTEND_SITE_JFROG_TOKEN }}
      - name: validate connectivity with jfrog server
        run: |
          jf rt ping
